package com.rohila.api.exception;

import com.rohila.api.response.Message;
import org.springframework.http.HttpStatus;

import java.util.List;

/**
 * Class file to create custom exception of {@link ApiRequestException}
 *
 * @author Tarun Rohila
 */
public class ApiRequestException extends ApiException {

    /**
     * Autogenerated serial version id
     */
    private static final long serialVersionUID = 2920254111746084643L;

    /**
     * Constructor declaration
     *
     * @param message - message
     */
    public ApiRequestException(Message message) {
        super(message);
    }

    /**
     * Constructor declaration
     *
     * @param message   - message
     * @param throwable - throwable
     */
    public ApiRequestException(Message message, Throwable throwable) {
        super(message, throwable);
    }

    /**
     * Constructor declaration
     *
     * @param messages - messages
     */
    public ApiRequestException(List<Message> messages) {
        super(messages);
    }

    /**
     * Method to get status
     *
     * @return status
     */
    @Override
    public HttpStatus getStatus() {
        return HttpStatus.BAD_REQUEST;
    }
}
